import { Info, Database, FlaskConical } from "lucide-react";

/**
 * DataModeBanner
 * Clearly communicates data provenance: controlled synthetic demo dataset (default).
 * OpenDengue / NASA POWER are retained as optional experimental pathways only.
 */
export default function DataModeBanner() {
  return (
    <div className="rounded-xl border border-sky-200 bg-sky-50 px-5 py-4 shadow-sm">
      {/* Header row */}
      <div className="flex items-start gap-3">
        <div className="mt-0.5 flex-shrink-0 rounded-md bg-sky-100 p-1.5">
          <Database className="h-4 w-4 text-sky-700" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-semibold text-sky-900">
              Data Provenance
            </span>
            <span className="inline-flex items-center gap-1 rounded-full bg-sky-100 px-2 py-0.5 text-xs font-medium text-sky-700 border border-sky-200">
              Current Mode: Controlled Weekly Demonstration Dataset
            </span>
            <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700 border border-amber-200">
              <FlaskConical className="h-3 w-3" />
              Prototype
            </span>
          </div>

          {/* Detail bullets */}
          <ul className="mt-2 space-y-1 text-xs text-sky-800 list-none">
            <li className="flex items-start gap-1.5">
              <span className="mt-0.5 text-sky-500 font-bold">·</span>
              <span>
                <strong>Dengue case data: synthetic/demo.</strong> Controlled weekly Dhaka South
                data (2024–2026, up to week 24) generated by{" "}
                <code className="font-mono text-sky-700 bg-sky-100 px-0.5 rounded">
                  analytics/generate_demo_data.py
                </code>{" "}
                with a realistic seasonal pattern (pre-monsoon rise, 2025 peak surge, early 2026 warning).
              </span>
            </li>
            <li className="flex items-start gap-1.5">
              <span className="mt-0.5 text-sky-400 font-bold">·</span>
              <span>
                <strong>Climate data: synthetic/demo.</strong> Weekly Dhaka South climate variables
                (rainfall, temperature, humidity) with seasonal monsoon variation — aligned to the
                same 2024–2026 dengue case period to support lagged feature engineering.
              </span>
            </li>
            <li className="flex items-start gap-1.5">
              <span className="mt-0.5 text-sky-400 font-bold">·</span>
              Zone allocation, facility inventory, bed occupancy, and readiness values are
              <strong> synthetic demonstration values</strong> (no official sub-national
              surveillance data exists at this resolution). Real public hospital names are used
              as credible location anchors only.
            </li>
            <li className="flex items-start gap-1.5">
              <span className="mt-0.5 text-sky-400 font-bold">·</span>
              No patient-level data is used or stored anywhere in this system.
            </li>
            <li className="flex items-start gap-1.5">
              <span className="mt-0.5 text-amber-500 font-bold">·</span>
              <span>
                Optional OpenDengue and NASA POWER integration is available via{" "}
                <code className="font-mono text-sky-700 bg-sky-100 px-0.5 rounded">
                  --use-opendengue
                </code>{" "}
                and{" "}
                <code className="font-mono text-sky-700 bg-sky-100 px-0.5 rounded">
                  --use-nasa-power-climate
                </code>{" "}
                flags for future real-data validation, but is not the active demo mode.
              </span>
            </li>
          </ul>
        </div>
      </div>

      {/* Footer note */}
      <div className="mt-3 flex items-center gap-1.5 border-t border-sky-200 pt-3">
        <Info className="h-3.5 w-3.5 text-sky-500 flex-shrink-0" />
        <p className="text-xs text-sky-600">
          Operational outputs are advisory only. Human expert review is required before
          any real-world use.
        </p>
      </div>
    </div>
  );
}
