/**
 * demo-data.ts
 *
 * Exports analytics outputs as typed objects for client components.
 *
 * Primary sources:  Generated JSON files under data/ (analytics pipeline output)
 * Fallback sources: data/placeholder/ for items not yet covered by the pipeline
 *                   (feature_importance, validation_metrics shape).
 */

// ── Generated by analytics pipeline ─────────────────────────────────────────
import forecastOutputRaw from "@/data/forecast_output.json";
import zonesRaw from "@/data/zones.json";
import facilitiesRaw from "@/data/facilities.json";
import inventoryRaw from "@/data/inventory.json";
// directives.json is a wrapper object: { directives: [...], summary: {...}, ... }
import directivesFileRaw from "@/data/directives.json";
// Dashboard-ready outputs from analytics/dashboard_exporter.py
import dashboardSummaryRaw from "@/data/dashboard_summary.json";
import modelComparisonRaw from "@/data/model_comparison.json";
import chartDataRaw from "@/data/chart_data.json";
// Pipeline run log
import pipelineRunSummaryRaw from "@/data/pipeline_run_summary.json";

// ── Placeholder (pipeline does not yet produce these shapes) ─────────────────
import validationMetricsRaw from "@/data/placeholder/validation_metrics.json";
import featureImportanceRaw from "@/data/placeholder/feature_importance.json";

import type {
  ForecastOutput,
  ValidationMetrics,
  FeatureImportanceItem,
  Zone,
  Facility,
  Inventory,
  Directive,
  DashboardSummary,
  PipelineRunSummary,
} from "./types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const directivesFile = directivesFileRaw as any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const dashboardSummaryAny = dashboardSummaryRaw as any;

export const forecastOutput = forecastOutputRaw as unknown as ForecastOutput;
export const validationMetrics = validationMetricsRaw as unknown as ValidationMetrics;
export const featureImportance = featureImportanceRaw as FeatureImportanceItem[];
export const zones = zonesRaw as unknown as Zone[];
export const facilities = facilitiesRaw as unknown as Facility[];
export const inventory = inventoryRaw as unknown as Inventory[];
export const directives = (directivesFile.directives ?? []) as Directive[];
export const directivesSummary = directivesFile.summary as {
  total_zones: number;
  total_facilities: number;
  total_public_government_anchors: number;
  facilities_with_expected_bed_gap: number;
  facilities_with_worst_case_bed_gap: number;
  critical_supply_alerts: number;
  highest_priority_zone: string;
  highest_pressure_facility: string;
};

// ── Dashboard-ready outputs ──────────────────────────────────────────────────
export const dashboardSummary = dashboardSummaryAny as DashboardSummary;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const modelComparison = modelComparisonRaw as any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const chartData = chartDataRaw as any;
export const pipelineRunSummary = pipelineRunSummaryRaw as unknown as PipelineRunSummary;
